function run_cardsync_interslice( reconDir )
%RUN_CARDSYNC_INTERSLICE  Synchcronise cardiac cycles between slice-locations.
%
%   RUN_CARDSYNC_INTERSLICE( reconDir ) runs interslice cardiac synchronization for data in directory reconDIR.
%
%   Expects folder structure (e.g., for reconDir='/home/user/fetal_cmr_4d_recons/case_name')
%
%       reconDir  
%       ├── cardsync
%       ├── data
%       └── slice_cine_vol
% 
%   with files as generated by this fetal_cmr_4d framework.
%
%   See also PREPROC, CARDSYNC_INTERSLICE.

% setup
dataDir     = fullfile( reconDir, 'data' );
cardsyncDir = fullfile( reconDir, 'cardsync' );
cineDir     = fullfile( reconDir, 'slice_cine_vol' );    
M = matfile( fullfile( cardsyncDir, 'results_cardsync_intraslice.mat' ) );

% target slice
tgtLoc = NaN;
tgtLocFile = fullfile( dataDir, 'tgt_slice_no.txt' );
if exist( tgtLocFile , 'file' )
    fid = fopen( tgtLocFile, 'r' );
    tgtLoc = fscanf( fid, '%f' );
    fclose( fid );
end

% excluded slices
excludeSlice = [];
excludeSliceFile = fullfile( dataDir, 'force_exclude_slice.txt' );
if exist( excludeSliceFile , 'file' )
    fid = fopen( excludeSliceFile, 'r' );
    excludeSlice = fscanf( fid, '%f' ) + 1;  % NOTE: slice locations in input file are zero-indexed
    fclose( fid );
end

% slice-slice cardiac synchronisation
cardsync_interslice( M.S, 'recondir', cineDir, 'resultsdir', cardsyncDir, 'tgtloc', tgtLoc, 'excludeloc', excludeSlice );